--- #YAML:1.0
name:               Statistics-CountAverage-XS
version:            0.01
abstract:           XS implementation of Statistics::CountAverage
author:
    - Ildar Efremov <iefremov@suse.de>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
